-- 3 slot
INSERT INTO Weapons(name, size, price, unlock_level) VALUES ('Bomb Lance', 3, 199, 78);
INSERT INTO Weapons(name, size, price, unlock_level) VALUES ('Caldwell Rival 78', 3, 100, 18);
INSERT INTO Weapons(name, size, price, unlock_level) VALUES ('Crossbow', 3, 73, 4);
INSERT INTO Weapons(name, size, price, unlock_level) VALUES ('Crown & King Auto-5', 3, 600, 82);
INSERT INTO Weapons(name, size, price, unlock_level) VALUES ('Lebel 1886', 3, 397, 52);
INSERT INTO Weapons(name, size, price, unlock_level) VALUES ('Lebel 1886 Marksman', 3, 437, 52);
INSERT INTO Weapons(name, size, price, unlock_level) VALUES ('Lebel 1886 Talon', 3, 437, 52);
INSERT INTO Weapons(name, size, price, unlock_level) VALUES ('Martini-Henry IC1', 3, 145, 16);
INSERT INTO Weapons(name, size, price, unlock_level) VALUES ('Martini-Henry IC1 Marksman', 3, 173, 16);
INSERT INTO Weapons(name, size, price, unlock_level) VALUES ('Martini-Henry IC1 Riposte', 3, 164, 16);
INSERT INTO Weapons(name, size, price, unlock_level) VALUES ('Mosin-Nagant M1891', 3, 490, 72);
INSERT INTO Weapons(name, size, price, unlock_level) VALUES ('Mosin-Nagant M1891 Avtomat', 3, 1250, 72);
INSERT INTO Weapons(name, size, price, unlock_level) VALUES ('Mosin-Nagant M1891 Bayonet', 3, 540, 72);
INSERT INTO Weapons(name, size, price, unlock_level) VALUES ('Mosin-Nagant M1891 Sniper', 3, 550, 72);
INSERT INTO Weapons(name, size, price, unlock_level) VALUES ('Nagant M1895 Officer Carbine', 3, 155, 36);
INSERT INTO Weapons(name, size, price, unlock_level) VALUES ('Nagant M1895 Officer Carbine Deadeye', 3, 211, 36);
INSERT INTO Weapons(name, size, price, unlock_level) VALUES ('Nitro Express Rifle', 3, 1015, 88);
INSERT INTO Weapons(name, size, price, unlock_level) VALUES ('Romero 77', 3, 34, 1);
INSERT INTO Weapons(name, size, price, unlock_level) VALUES ('Romero 77 Talon', 3, 59, 1);
INSERT INTO Weapons(name, size, price, unlock_level) VALUES ('Sparks LRR', 3, 130, 26);
INSERT INTO Weapons(name, size, price, unlock_level) VALUES ('Sparks LRR Silencer', 3, 150, 26);
INSERT INTO Weapons(name, size, price, unlock_level) VALUES ('Sparks LRR Sniper', 3, 199, 26);
INSERT INTO Weapons(name, size, price, unlock_level) VALUES ('Specter 1882', 3, 188, 58);
INSERT INTO Weapons(name, size, price, unlock_level) VALUES ('Specter 1882 Bayonet', 3, 223, 58);
INSERT INTO Weapons(name, size, price, unlock_level) VALUES ('Springfield 1866', 3, 38, 1);
INSERT INTO Weapons(name, size, price, unlock_level) VALUES ('Springfield 1866 Marksman', 3, 73, 1);
INSERT INTO Weapons(name, size, price, unlock_level) VALUES ('Vetterli 71 Karabiner', 3, 105, 6);
INSERT INTO Weapons(name, size, price, unlock_level) VALUES ('Vetterli 71 Karabiner Bayonet', 3, 155, 6);
INSERT INTO Weapons(name, size, price, unlock_level) VALUES ('Vetterli 71 Karabiner Deadeye', 3, 130, 6);
INSERT INTO Weapons(name, size, price, unlock_level) VALUES ('Winfield M1873', 3, 75, 42);
INSERT INTO Weapons(name, size, price, unlock_level) VALUES ('Winfield M1873 Aperture', 3, 80, 42);
INSERT INTO Weapons(name, size, price, unlock_level) VALUES ('Winfield M1873 Musket Bayonet', 3, 137, 42);
INSERT INTO Weapons(name, size, price, unlock_level) VALUES ('Winfield M1873 Swift', 3, 128, 42);
INSERT INTO Weapons(name, size, price, unlock_level) VALUES ('Winfield M1873 Talon', 3, 100, 42);
INSERT INTO Weapons(name, size, price, unlock_level) VALUES ('Winfield M1873C', 3, 41, 1);
INSERT INTO Weapons(name, size, price, unlock_level) VALUES ('Winfield M1873C Marksman', 3, 56, 1);
INSERT INTO Weapons(name, size, price, unlock_level) VALUES ('Winfield M1873C Silencer', 3, 55, 1);
INSERT INTO Weapons(name, size, price, unlock_level) VALUES ('Winfield M1873C Silencer', 3, 55, 1);
INSERT INTO Weapons(name, size, price, unlock_level) VALUES ('Winfield M1876 Centennial', 3, 338, 58);
INSERT INTO Weapons(name, size, price, unlock_level) VALUES ('Winfield 1887 Terminus', 3, 309, 64);

-- 2 slot
INSERT INTO Weapons(name, size, price, unlock_level) VALUES ('Bornheim No. 3 Match', 2, 224, 30);
INSERT INTO Weapons(name, size, price, unlock_level) VALUES ('Caldwell Rival 78 Handcannon', 2, 85, 18);
INSERT INTO Weapons(name, size, price, unlock_level) VALUES ('Combat Axe', 2, 5, 1);
INSERT INTO Weapons(name, size, price, unlock_level) VALUES ('Dolch 96 Precision', 2, 790, 68);
INSERT INTO Weapons(name, size, price, unlock_level) VALUES ('Mosin-Nagant M1891 Obrez', 2, 290, 72);
INSERT INTO Weapons(name, size, price, unlock_level) VALUES ('Mosin-Nagant M1891 Obrez Drum', 2, 350, 72);
INSERT INTO Weapons(name, size, price, unlock_level) VALUES ('Mosin-Nagant M1891 Obrez Mace', 2, 310, 72);
INSERT INTO Weapons(name, size, price, unlock_level) VALUES ('Nagant M1895 Deadeye', 2, 42, 1);
INSERT INTO Weapons(name, size, price, unlock_level) VALUES ('Nagant M1895 Precision', 2, 29, 1);
INSERT INTO Weapons(name, size, price, unlock_level) VALUES ('Romero 88 Handcannon', 2, 26, 1);
INSERT INTO Weapons(name, size, price, unlock_level) VALUES ('Romero 88 Hatchet', 2, 62, 1);
INSERT INTO Weapons(name, size, price, unlock_level) VALUES ('Specter 1882 Compact', 2, 164, 58);
INSERT INTO Weapons(name, size, price, unlock_level) VALUES ('Springfield 1866 Compact', 2, 33, 1);
INSERT INTO Weapons(name, size, price, unlock_level) VALUES ('Springfield 1866 Compact Deadeye', 2, 46, 1);
INSERT INTO Weapons(name, size, price, unlock_level) VALUES ('Springfield 1866 Compact Striker', 2, 56, 1);
INSERT INTO Weapons(name, size, price, unlock_level) VALUES ('Winfield M1873C Vandal', 2, 35, 1);
INSERT INTO Weapons(name, size, price, unlock_level) VALUES ('Winfield M1873C Vandal Striker', 2, 39, 1);
INSERT INTO Weapons(name, size, price, unlock_level) VALUES ('Winfield M1873C Vandal Deadeye', 2, 45, 1);
INSERT INTO Weapons(name, size, price, unlock_level) VALUES ('Winfield 1887 Terminus Handcannon', 2, 289, 64);

-- 1 slot
INSERT INTO Weapons(name, size, price, unlock_level) VALUES ('Bornheim No. 3', 1, 301, 30);
INSERT INTO Weapons(name, size, price, unlock_level) VALUES ('Bornheim No. 3 Extended', 1, 306, 30);
INSERT INTO Weapons(name, size, price, unlock_level) VALUES ('Caldwell Conversion Chain Pistol', 1, 50, 22);
INSERT INTO Weapons(name, size, price, unlock_level) VALUES ('Caldwell Conversion Pistol', 1, 26, 22);
INSERT INTO Weapons(name, size, price, unlock_level) VALUES ('Caldwell Conversion Uppercut', 1, 275, 22);
INSERT INTO Weapons(name, size, price, unlock_level) VALUES ('Caldwell Pax', 1, 100, 10);
INSERT INTO Weapons(name, size, price, unlock_level) VALUES ('Caldwell Pax Claw', 1, 125, 10);
INSERT INTO Weapons(name, size, price, unlock_level) VALUES ('Cavalry Saber', 1, 60, 62);
INSERT INTO Weapons(name, size, price, unlock_level) VALUES ('Dolch 96', 1, 750, 68);
INSERT INTO Weapons(name, size, price, unlock_level) VALUES ('Hand Crossbow', 1, 35, 4);
INSERT INTO Weapons(name, size, price, unlock_level) VALUES ('LeMat Mark II Revolver', 1, 95, 46);
INSERT INTO Weapons(name, size, price, unlock_level) VALUES ('Machete', 1, 18, 12);
INSERT INTO Weapons(name, size, price, unlock_level) VALUES ('Nagant M1895', 1, 24, 1);
INSERT INTO Weapons(name, size, price, unlock_level) VALUES ('Nagant M1895 Officer', 1, 66, 36);
INSERT INTO Weapons(name, size, price, unlock_level) VALUES ('Nagant M1895 Officer Brawler', 1, 80, 36);
INSERT INTO Weapons(name, size, price, unlock_level) VALUES ('Nagant M1895 Silencer', 1, 53, 1);

-- tools
INSERT INTO Tools(name, price, unlock_level) VALUES ('Alert trip Mine', 60, 32);
INSERT INTO Tools(name, price, unlock_level) VALUES ('Blank Fire Decoys', 45, 11);
INSERT INTO Tools(name, price, unlock_level) VALUES ('Choke Bomb', 25, 11);
INSERT INTO Tools(name, price, unlock_level) VALUES ('Concertine Trip Mine', 90, 40);
INSERT INTO Tools(name, price, unlock_level) VALUES ('Decoy Fuses', 60, 11);
INSERT INTO Tools(name, price, unlock_level) VALUES ('Decoys', 5, 32);
INSERT INTO Tools(name, price, unlock_level) VALUES ('Dusters', 15, 20);
INSERT INTO Tools(name, price, unlock_level) VALUES ('Electric Lamp', 5, 1);
INSERT INTO Tools(name, price, unlock_level) VALUES ('First Aid Kit', 30, 1);
INSERT INTO Tools(name, price, unlock_level) VALUES ('Flare Pistol', 36, 1);
INSERT INTO Tools(name, price, unlock_level) VALUES ('Fusees', 10, 1);
INSERT INTO Tools(name, price, unlock_level) VALUES ('Heavy Knife', 25, 1);
INSERT INTO Tools(name, price, unlock_level) VALUES ('Knife', 20, 1);
INSERT INTO Tools(name, price, unlock_level) VALUES ('Knuckle Knife', 15, 1);
INSERT INTO Tools(name, price, unlock_level) VALUES ('Poison Trip Mine', 60, 48);
INSERT INTO Tools(name, price, unlock_level) VALUES ('Quad Derringer', 30, 66);
INSERT INTO Tools(name, price, unlock_level) VALUES ('Splyglass', 8, 24);
INSERT INTO Tools(name, price, unlock_level) VALUES ('Throwing Knives', 40, 1);

-- consumables
INSERT INTO Consumables(name, price, unlock_level) VALUES ('Ammo Box', 65, 80);
INSERT INTO Consumables(name, price, unlock_level) VALUES ('Antidote Shot', 55, 48);
INSERT INTO Consumables(name, price, unlock_level) VALUES ('Big Dynamite Bundle', 110, 8);
INSERT INTO Consumables(name, price, unlock_level) VALUES ('Chaos Bomb', 15, 32);
INSERT INTO Consumables(name, price, unlock_level) VALUES ('Concertina Bomb', 48, 40);
INSERT INTO Consumables(name, price, unlock_level) VALUES ('Dynamite Bundle', 75, 8);
INSERT INTO Consumables(name, price, unlock_level) VALUES ('Dynamite Stick', 18, 8);
INSERT INTO Consumables(name, price, unlock_level) VALUES ('Fire Bomb', 18, 1);
INSERT INTO Consumables(name, price, unlock_level) VALUES ('Flash Bomb', 47, 40);
INSERT INTO Consumables(name, price, unlock_level) VALUES ('Frag Bomb', 70, 8);
INSERT INTO Consumables(name, price, unlock_level) VALUES ('Hellfire Bomb', 70, 1);
INSERT INTO Consumables(name, price, unlock_level) VALUES ('Hive Bomb', 40, 48);
INSERT INTO Consumables(name, price, unlock_level) VALUES ('Liquid Fire Bomb', 23, 1);
INSERT INTO Consumables(name, price, unlock_level) VALUES ('Poison Bomb', 25, 48);
INSERT INTO Consumables(name, price, unlock_level) VALUES ('Stamina Shot', 40, 1);
INSERT INTO Consumables(name, price, unlock_level) VALUES ('Sticky Bomb', 64, 8);
INSERT INTO Consumables(name, price, unlock_level) VALUES ('Vitality Shot', 65, 1);
INSERT INTO Consumables(name, price, unlock_level) VALUES ('Waxed Dynamite Stick', 24, 8);
INSERT INTO Consumables(name, price, unlock_level) VALUES ('Weak Antidote Shot', 25, 48);
INSERT INTO Consumables(name, price, unlock_level) VALUES ('Weak Stamina Shot', 10, 1);
INSERT INTO Consumables(name, price, unlock_level) VALUES ('Weak Vitality Shots', 10, 1);
